repository: 'testsmt/testsmt.github.io'
url: "https://testsmt.github.io"

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-redirect-from # see https://docs.github.com/en/enterprise/2.13/user/articles/redirects-on-github-pages
  - jekyll-include-cache # required by the minimal-mistakes theme

title: Project Yin-Yang for SMT Solver Testing # Can we find a better name?

# Make stuff in _conferences accessible from /
collections:
  conferences:
    output: true
    permalink: /:path

# Apply the default layout to all files (= empty path)
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      classes: "wide"

logo: "./img/tool_logo.png"


twitter:
  username: "testsmtsolvers "

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mmistakes"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mmistakes"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/mmistakes"

sidebar:
  nav: "docs"